export const clone_template = [
  {
    repo_name: "textutils",
    clone_url: "https://github.com/shubham9069/textutiles.git",
    default_branch: "master",
    language: "javascript",
    repo_url: "shubham9069/textutiles",
    frame_work: "React.js",
    icon: "/image/icon/react-icon.svg",
    img: "/image/reactjs.png",
  },
  {
    repo_name: "next-template",
    clone_url: `https://github.com/shubham9069/template-clone.git`,
    default_branch: "master",
    language: "javascript",
    repo_url: "shubham9069/template-clone",
    frame_work: "Next.js",
    icon: "/image/icon/next-icon.svg",
    img: "/image/nextjs.avif",
  },
  {
    repo_name: "angular-template",
    clone_url:"-b angular-template https://github.com/shubham9069/template-clone.git",
    default_branch: "angular-template",
    language: "javascript",
    repo_url: "shubham9069/template-clone",
    frame_work: "Angular.js",
    icon: "/image/icon/angular-icon.png",
    img: "/image/angularjs.png",
  },
];